version: '3'

services:
  # --------------
  # registry
  # --------------
  discovery:
    build: ../registry/target
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - redis-net

  # --------------
  # zuul proxy
  # --------------
  zuul:
    build: ../proxy/target
    ports:
      - "80:8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - redis-net

  # --------------
  # support
  # --------------
  support:
    build: ../support/target
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis

  # --------------
  # cataloger-manager
  # --------------
  catalogermanager:
    build: ../catalogermanager/target
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis

  # --------------
  # cataloger-business
  # --------------
  catalogerbusiness:
    build: ../catalogerbusiness/target
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis
  # --------------
  # Redis
  # --------------    
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    links:
      - discovery
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
    redis-net:
volumes:
    redis-data:


