version: '3'

services:
  # --------------
  # registry
  # --------------
  discovery:
    build: ../registry/target
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # zuul proxy
  # --------------
  zuul:
    build: ../proxy/target
    ports:
      - "80:8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # support
  # --------------
  support:
    build: ../support/target
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # cataloger-manager
  # --------------
  catalogermanager:
    build: ../catalogermanager/target
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # --------------
  # cataloger-business
  # --------------
  catalogerbusiness:
    build: ../catalogerbusiness/target
    ports:
      - "8080"
    links:
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker


